version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8082:8082"
    expose :
      - 8082
      - 8081 
    networks:
      sonarqube-postgres:
        ipv4_address: 172.20.0.10
       
volumes:
  nexus-data: {}
networks:
  sonarqube-postgres:
    name: sonarqube-postgres
