version: "3"
services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube

    environment:
      - SONARQUBE_JDBC_USERNAME=wissem
      - SONARQUBE_JDBC_PASSWORD=Admin123
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:54322/postgres
    ports:
      - "9001:9000"
    links:
      - postgres
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarqube-postgres 
  postgres:
    image: postgres
    container_name: postgres_sql
    environment:
      - POSTGRES_USER=wissem
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=postgres
    ports:
      - "54322:5432"
    volumes:
      - sonarqube_postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sonarqube-postgres  
volumes:
  postgres_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_postgres:
  sonarqube_extensions:
networks:
  sonarqube-postgres:
    name: sonarqube-postgres 
